spring.application.name=ProjetoVendasSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_vendas
spring.datasource.username=postgres
spring.datasource.password=7267

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
